  
version: "3.7"
services:
  app:
    container_name: app
    build: ./app/
    volumes:
      - logs:/var/log/app/
    links:
      - filebeat
  
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.6.0
    volumes:
      - logs:/var/log/app/
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - logstash
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      start_period: 120s

  logstash:
    container_name: logstash
    image: logstash:7.6.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/logstash.conf
    ports:
      - "9600:9600"
    command: logstash -f /usr/share/logstash/logstash.conf


  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: kibana:7.6.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  logs: 